//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroFtpClient.Ftp.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetroFtpClient.Ftp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AddConnectionButtonText ähnelt.
        /// </summary>
        internal static string AddConnectionButtonText {
            get {
                return ResourceManager.GetString("AddConnectionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AddFilesToQueue ähnelt.
        /// </summary>
        internal static string AddFilesToQueue {
            get {
                return ResourceManager.GetString("AddFilesToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionAddedFailedStatusBarMessage ähnelt.
        /// </summary>
        internal static string ConnectionAddedFailedStatusBarMessage {
            get {
                return ResourceManager.GetString("ConnectionAddedFailedStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionAddedSuccessfullStatusBarMessage ähnelt.
        /// </summary>
        internal static string ConnectionAddedSuccessfullStatusBarMessage {
            get {
                return ResourceManager.GetString("ConnectionAddedSuccessfullStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionDeletedFailedStatusBarMessage ähnelt.
        /// </summary>
        internal static string ConnectionDeletedFailedStatusBarMessage {
            get {
                return ResourceManager.GetString("ConnectionDeletedFailedStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionDeletedSuccessfullStatusBarMessage ähnelt.
        /// </summary>
        internal static string ConnectionDeletedSuccessfullStatusBarMessage {
            get {
                return ResourceManager.GetString("ConnectionDeletedSuccessfullStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionEstablishmentFailed ähnelt.
        /// </summary>
        internal static string ConnectionEstablishmentFailed {
            get {
                return ResourceManager.GetString("ConnectionEstablishmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionEstablishmentSuccessful ähnelt.
        /// </summary>
        internal static string ConnectionEstablishmentSuccessful {
            get {
                return ResourceManager.GetString("ConnectionEstablishmentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionHost ähnelt.
        /// </summary>
        internal static string ConnectionHost {
            get {
                return ResourceManager.GetString("ConnectionHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionName ähnelt.
        /// </summary>
        internal static string ConnectionName {
            get {
                return ResourceManager.GetString("ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionPassword ähnelt.
        /// </summary>
        internal static string ConnectionPassword {
            get {
                return ResourceManager.GetString("ConnectionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionPort ähnelt.
        /// </summary>
        internal static string ConnectionPort {
            get {
                return ResourceManager.GetString("ConnectionPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionTimeout ähnelt.
        /// </summary>
        internal static string ConnectionTimeout {
            get {
                return ResourceManager.GetString("ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionType ähnelt.
        /// </summary>
        internal static string ConnectionType {
            get {
                return ResourceManager.GetString("ConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionUsername ähnelt.
        /// </summary>
        internal static string ConnectionUsername {
            get {
                return ResourceManager.GetString("ConnectionUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CopyUrlsToClipboard ähnelt.
        /// </summary>
        internal static string CopyUrlsToClipboard {
            get {
                return ResourceManager.GetString("CopyUrlsToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CreateDirectory ähnelt.
        /// </summary>
        internal static string CreateDirectory {
            get {
                return ResourceManager.GetString("CreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DelecteConnetionButtonText ähnelt.
        /// </summary>
        internal static string DelecteConnetionButtonText {
            get {
                return ResourceManager.GetString("DelecteConnetionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Delete ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DeleteQueueEntry ähnelt.
        /// </summary>
        internal static string DeleteQueueEntry {
            get {
                return ResourceManager.GetString("DeleteQueueEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Download ähnelt.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DownloadDirection ähnelt.
        /// </summary>
        internal static string DownloadDirection {
            get {
                return ResourceManager.GetString("DownloadDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DownloadFolder ähnelt.
        /// </summary>
        internal static string DownloadFolder {
            get {
                return ResourceManager.GetString("DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DownloadQueue ähnelt.
        /// </summary>
        internal static string DownloadQueue {
            get {
                return ResourceManager.GetString("DownloadQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DownloadQueueFinished ähnelt.
        /// </summary>
        internal static string DownloadQueueFinished {
            get {
                return ResourceManager.GetString("DownloadQueueFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Filename ähnelt.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @FileOwner ähnelt.
        /// </summary>
        internal static string FileOwner {
            get {
                return ResourceManager.GetString("FileOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @FilePermissions ähnelt.
        /// </summary>
        internal static string FilePermissions {
            get {
                return ResourceManager.GetString("FilePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Filesize ähnelt.
        /// </summary>
        internal static string Filesize {
            get {
                return ResourceManager.GetString("Filesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Filetype ähnelt.
        /// </summary>
        internal static string Filetype {
            get {
                return ResourceManager.GetString("Filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @FtpConnectionsFlyoutTitle ähnelt.
        /// </summary>
        internal static string FtpConnectionsFlyoutTitle {
            get {
                return ResourceManager.GetString("FtpConnectionsFlyoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @LastModified ähnelt.
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @OpenTargetFolderInExplorer ähnelt.
        /// </summary>
        internal static string OpenTargetFolderInExplorer {
            get {
                return ResourceManager.GetString("OpenTargetFolderInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Permissions ähnelt.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @QueueEntryDownloadProgress ähnelt.
        /// </summary>
        internal static string QueueEntryDownloadProgress {
            get {
                return ResourceManager.GetString("QueueEntryDownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @QueueEntryDownloadSpeed ähnelt.
        /// </summary>
        internal static string QueueEntryDownloadSpeed {
            get {
                return ResourceManager.GetString("QueueEntryDownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @QueueEntryLocalPath ähnelt.
        /// </summary>
        internal static string QueueEntryLocalPath {
            get {
                return ResourceManager.GetString("QueueEntryLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @QueueEntryRemotePath ähnelt.
        /// </summary>
        internal static string QueueEntryRemotePath {
            get {
                return ResourceManager.GetString("QueueEntryRemotePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @QueueEntryStatus ähnelt.
        /// </summary>
        internal static string QueueEntryStatus {
            get {
                return ResourceManager.GetString("QueueEntryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Refresh ähnelt.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Rename ähnelt.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ServerPath ähnelt.
        /// </summary>
        internal static string ServerPath {
            get {
                return ResourceManager.GetString("ServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @StartDownload ähnelt.
        /// </summary>
        internal static string StartDownload {
            get {
                return ResourceManager.GetString("StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @StartQueueEntry ähnelt.
        /// </summary>
        internal static string StartQueueEntry {
            get {
                return ResourceManager.GetString("StartQueueEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @StopDownload ähnelt.
        /// </summary>
        internal static string StopDownload {
            get {
                return ResourceManager.GetString("StopDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @StopQueueEntry ähnelt.
        /// </summary>
        internal static string StopQueueEntry {
            get {
                return ResourceManager.GetString("StopQueueEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UpdateConnectionButtonText ähnelt.
        /// </summary>
        internal static string UpdateConnectionButtonText {
            get {
                return ResourceManager.GetString("UpdateConnectionButtonText", resourceCulture);
            }
        }
    }
}
