//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroFtpClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetroFtpClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AddNewConnection ähnelt.
        /// </summary>
        internal static string AddNewConnection {
            get {
                return ResourceManager.GetString("AddNewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ApplicationAccentColor ähnelt.
        /// </summary>
        internal static string ApplicationAccentColor {
            get {
                return ResourceManager.GetString("ApplicationAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ApplicationDllDescription ähnelt.
        /// </summary>
        internal static string ApplicationDllDescription {
            get {
                return ResourceManager.GetString("ApplicationDllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ApplicationDllName ähnelt.
        /// </summary>
        internal static string ApplicationDllName {
            get {
                return ResourceManager.GetString("ApplicationDllName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ApplicationDllVersion ähnelt.
        /// </summary>
        internal static string ApplicationDllVersion {
            get {
                return ResourceManager.GetString("ApplicationDllVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ApplicationInfo ähnelt.
        /// </summary>
        internal static string ApplicationInfo {
            get {
                return ResourceManager.GetString("ApplicationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ApplicationLanguage ähnelt.
        /// </summary>
        internal static string ApplicationLanguage {
            get {
                return ResourceManager.GetString("ApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ApplicationReadyStatusBarMessage ähnelt.
        /// </summary>
        internal static string ApplicationReadyStatusBarMessage {
            get {
                return ResourceManager.GetString("ApplicationReadyStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ApplicationSettings ähnelt.
        /// </summary>
        internal static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Theme ähnelt.
        /// </summary>
        internal static string ApplicationTheme {
            get {
                return ResourceManager.GetString("ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Components ähnelt.
        /// </summary>
        internal static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @Connect ähnelt.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DeleteConnection ähnelt.
        /// </summary>
        internal static string DeleteConnection {
            get {
                return ResourceManager.GetString("DeleteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @EditConnection ähnelt.
        /// </summary>
        internal static string EditConnection {
            get {
                return ResourceManager.GetString("EditConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @InstalledNetFrameworkVersions ähnelt.
        /// </summary>
        internal static string InstalledNetFrameworkVersions {
            get {
                return ResourceManager.GetString("InstalledNetFrameworkVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @IntroductionMessage ähnelt.
        /// </summary>
        internal static string IntroductionMessage {
            get {
                return ResourceManager.GetString("IntroductionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ModulVersions ähnelt.
        /// </summary>
        internal static string ModulVersions {
            get {
                return ResourceManager.GetString("ModulVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @NetFramework ähnelt.
        /// </summary>
        internal static string NetFramework {
            get {
                return ResourceManager.GetString("NetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @NetFrameworkClientProfile ähnelt.
        /// </summary>
        internal static string NetFrameworkClientProfile {
            get {
                return ResourceManager.GetString("NetFrameworkClientProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @NetFrameworkInfo ähnelt.
        /// </summary>
        internal static string NetFrameworkInfo {
            get {
                return ResourceManager.GetString("NetFrameworkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @NetFrameworkInstallPath ähnelt.
        /// </summary>
        internal static string NetFrameworkInstallPath {
            get {
                return ResourceManager.GetString("NetFrameworkInstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @NetFrameworkServicePack ähnelt.
        /// </summary>
        internal static string NetFrameworkServicePack {
            get {
                return ResourceManager.GetString("NetFrameworkServicePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @NetFrameworkVersion ähnelt.
        /// </summary>
        internal static string NetFrameworkVersion {
            get {
                return ResourceManager.GetString("NetFrameworkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @OsInformation ähnelt.
        /// </summary>
        internal static string OsInformation {
            get {
                return ResourceManager.GetString("OsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @OverviewPageTitle ähnelt.
        /// </summary>
        internal static string OverviewPageTitle {
            get {
                return ResourceManager.GetString("OverviewPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @WelcomeMessage ähnelt.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
